# .github/workflows/deploy.yml
name: Falcon-7B CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pip install pytest
        pytest -v tests/

  deploy-prod:
    needs: [build-test]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ec2-user
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          # Clone/update repository
          if [ -d "falcon-api" ]; then
            cd falcon-api
            git pull origin main
          else
            git clone https://github.com/chumbacash/falcon-api.git
            cd falcon-api
          fi
          
          # Install dependencies
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          
          # Setup environment
          cp .env.example .env
          
          # Restart service
          sudo systemctl restart falcon-api